### ISSUE TITLE
consult chlorophyll-transect-rosette package for samples lacking metadata

### ISSUE THREAD

**Issue by katemorkeski** [WHOIGit/nes-lter-nutrient-transect#23]
File in chlorophyll repo is samples_lacking_bottle_metadata-v2.csv

**Comment by ecrockford** [comment]
A small number of samples are lacking bottle metadata for one reason or another. In the nes-lter-chl-transect package, we crated a file samples_lacking_bottle_metadata-v2.csv that was made manually to input these metadata values for samples that would otherwise be NA. I think the code in chl package removes sample rows without metadata and then uses this file to add them back in. I think it would be nice to provide rows regardless of if they have metadata, and then insert these manual metadata values where appropriate.

**Comment by joannekoch** [comment]
@ecrockford , three issues/questions regarding samples_lacking_bottle_metadata-v2.csv:
1. Why are there zero values for cast and niskin for ar24b and ar38?
2. Was this file built and meant to be used for chl data and not nut data? columns in the samples data that are not in nut data: method_contributor, filter size, chl, phaeo, iode_quality flag. Likewise there there columns in nut data not in samples: sample_id, nitrate, ammon, phosophate, silicate, alt sample id.
3. This file should follow these rules and it does not: For string and date/time columns, an empty cell, For numeric columns, "NaN".
